# petstore docker-compose

version: "2"

services:
  openvpn:
    image: kylemanna/openvpn:2.0.0
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data:/etc/openvpn
    cap_add:
      - NET_ADMIN

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petstore
      character-set-server: utf8mb4

  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: rabbitmq
    ports:
      - "15672:15672"

  eureka:
    image: petstore-eureka:0.0.1-SNAPSHOT
    container_name: petstore-eureka
    ports:
      - "8761:8761"
    volumes:
      - /tmp

  config:
    image: petstore-config:0.0.1-SNAPSHOT
    container_name: petstore-config
    ports:
      - "8888:8888"
    volumes:
      - /tmp

  account:
    image: petstore-account:0.0.1-SNAPSHOT
    container_name: petstore-account
    ports:
      - "9001:9001"
    volumes:
      - /tmp
