### application config for native profile ###

# spring config:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP}:3306/petstore?useSSL=false&autoReconnect=true
    username: root
    # get encrypted string by:
    # curl -d 'original-string' http://<config-server>:8888/encrypt
    password: '{cipher}b38de5599e160c5d83ef67f9ba660f1a77c0e8527dba9d2dd99bc59e564e2bb8'
  jpa:
    show-sql: true
    database: mysql
    properties:
      javax:
        persistence:
          # generate DDL script under target/init.sql,
          # but not execute on startup:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: target/init.sql
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# default http port is set to 8080:
server:
  port: 8080

# timeout for rest invocation:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

# eureka config:
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:8761/eureka/
